# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_torchoptx_sgd <- function(params) {
    .Call('_torchoptx_rcpp_torchoptx_sgd', PACKAGE = 'torchoptx', params)
}

rcpp_torchoptx_sgd_step <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_sgd_step', PACKAGE = 'torchoptx', opt))
}

rcpp_torchoptx_sgd_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_sgd_zero_grad', PACKAGE = 'torchoptx', opt))
}

rcpp_delete_optim_sgd <- function(x) {
    invisible(.Call('_torchoptx_rcpp_delete_optim_sgd', PACKAGE = 'torchoptx', x))
}

optim_sgd_new <- function(params) {
    .Call('_torchoptx_optim_sgd_new', PACKAGE = 'torchoptx', params)
}

optim_sgd_step <- function(opt) {
    invisible(.Call('_torchoptx_optim_sgd_step', PACKAGE = 'torchoptx', opt))
}

optim_sgd_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_optim_sgd_zero_grad', PACKAGE = 'torchoptx', opt))
}

