# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_torchoptx_sgd <- function(params, lr, momentum, dampening, weight_decay, nesterov) {
    .Call('_torchoptx_rcpp_torchoptx_sgd', PACKAGE = 'torchoptx', params, lr, momentum, dampening, weight_decay, nesterov)
}

rcpp_torchoptx_sgd_step <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_sgd_step', PACKAGE = 'torchoptx', opt))
}

rcpp_torchoptx_sgd_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_sgd_zero_grad', PACKAGE = 'torchoptx', opt))
}

rcpp_torchoptx_adam <- function(params, lr, betas0, betas1, eps, weight_decay, amsgrad) {
    .Call('_torchoptx_rcpp_torchoptx_adam', PACKAGE = 'torchoptx', params, lr, betas0, betas1, eps, weight_decay, amsgrad)
}

rcpp_torchoptx_adam_step <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_adam_step', PACKAGE = 'torchoptx', opt))
}

rcpp_torchoptx_adam_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_rcpp_torchoptx_adam_zero_grad', PACKAGE = 'torchoptx', opt))
}

rcpp_delete_optim_sgd <- function(x) {
    invisible(.Call('_torchoptx_rcpp_delete_optim_sgd', PACKAGE = 'torchoptx', x))
}

rcpp_delete_optim_adam <- function(x) {
    invisible(.Call('_torchoptx_rcpp_delete_optim_adam', PACKAGE = 'torchoptx', x))
}

optim_sgd_new <- function(params, lr, momentum, dampening, weight_decay, nesterov) {
    .Call('_torchoptx_optim_sgd_new', PACKAGE = 'torchoptx', params, lr, momentum, dampening, weight_decay, nesterov)
}

optim_sgd_step <- function(opt) {
    invisible(.Call('_torchoptx_optim_sgd_step', PACKAGE = 'torchoptx', opt))
}

optim_sgd_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_optim_sgd_zero_grad', PACKAGE = 'torchoptx', opt))
}

optim_adam_new <- function(params, lr, betas0, betas1, eps, weight_decay, amsgrad) {
    .Call('_torchoptx_optim_adam_new', PACKAGE = 'torchoptx', params, lr, betas0, betas1, eps, weight_decay, amsgrad)
}

optim_adam_step <- function(opt) {
    invisible(.Call('_torchoptx_optim_adam_step', PACKAGE = 'torchoptx', opt))
}

optim_adam_zero_grad <- function(opt) {
    invisible(.Call('_torchoptx_optim_adam_zero_grad', PACKAGE = 'torchoptx', opt))
}

